/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.0
 * Generated at: 2022-05-17 05:40:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class studentregistration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<title>e-BhavishyaDwar</title>\r\n");
      out.write("<meta name=\"description\" content=\"website description\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"website keywords, website keywords\" />\r\n");
      out.write("<meta http-equiv=\"content-type\"\r\n");
      out.write("\tcontent=\"text/html; charset=windows-1252\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"style/style.css\"\r\n");
      out.write("\ttitle=\"style\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"main\">\r\n");
      out.write("\t\t<div id=\"header\">\r\n");
      out.write("\t\t\t<div id=\"logo\">\r\n");
      out.write("\t\t\t\t<div id=\"logo_text\">\r\n");
      out.write("\t\t\t\t\t<!-- class=\"logo_colour\", allows you to change the colour of the text -->\r\n");
      out.write("\t\t\t\t\t<h1 style=\"text-align:center \">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">STUDENT GUIDEFOR CAMPUS PLACEMENTS</a>\r\n");
      out.write("\t\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"menubar\">\r\n");
      out.write("\t\t\t\t<ul id=\"menu\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"login.jsp\">Login</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"studentregistration.jsp\">Student Registration</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"seniorregistration.jsp\">Senior Registration</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"companyregistration.jsp\">Company Registration</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"notification.jsp\">Notification</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"contact.jsp\">contact us</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"content_header\"></div>\r\n");
      out.write("\t\t<div id=\"site_content\">\r\n");
      out.write("\t\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t\t<!-- insert the page content here -->\r\n");
      out.write("\t\t\t\t");

					String status = request.getParameter("status");

					if (status != null) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<h1>");
      out.print(status);
      out.write("</h1>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<h1 style=\"text-align:center\">Student Registration</h1>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<form action=\"VoidmainServlet\" method=\"post\" name=\"appform\" enctype=\"multipart/form-data\" style=\" width: 50vw; margin-left : 15vw;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"type\" value=\"com.voidmain.pojo.Student\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"operation\" value=\"add\"> \r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"redirect\" value=\"studentregistration.jsp\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"form_settings\">\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<span>Name</span><input class=\"contact\" type=\"text\" name=\"name\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"\" required=\"required\"/>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<span>RollNumber</span><input class=\"contact\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"rno\" pattern=\"[1][89]BD1A0[0-9][0-9][A-Z 0-9]\" title=\"roll number should start with 18 or 19 ex:18BD1A054X\" value=\"\" required=\"required\"/>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<span>Password</span><input class=\"contact\" type=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"password\" pattern=\"(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}\" title=\"Minimum 8 characters,one Upper case,one lower case,one special character\" value=\"\" required=\"required\" />\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<span>Email Address</span><input class=\"contact\" type=\"email\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"email\" pattern=\"[a-z0-9](\\.?[a-z0-9]){3,}@[Gg][Mm][Aa][Ii][Ll]\\.com$\" title=\"please enter a valid e-mail ex:ex12@gmail.com\" value=\"\" required=\"required\"/>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<span>Mobile</span><input class=\"contact\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"mobile\" pattern=\"[6-9]\\d{9}\" title=\"please enter a valid Mobile Number\" value=\"\" required=\"required\"/>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<span>Branch</span><input class=\"contact\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"branch\" value=\"\" required=\"required\"/>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<span>Year</span><input class=\"contact\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"year\" value=\"\" required=\"required\"/>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<span>GPA</span><input class=\"contact\" type=\"number\" step=\"0.1\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"gpa\"  value=\"\" required=\"required\"/>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<span>Resume</span>\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"contact\" type=\"file\" name=\"resume\" value=\"\" required=\"required\"/>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<span>Address</span>\r\n");
      out.write("\t\t\t\t\t\t\t<textarea class=\"contact\" name=\"address\" required=\"required\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p style=\"padding-top: 15px\">\r\n");
      out.write("\t\t\t\t\t\t\t<span>&nbsp;</span><input class=\"submit\" type=\"submit\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"contact_submitted\" value=\"Register\" onclick=\"return validate()\" />\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
